language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - sudo apt-get update
   - sudo apt-get install cython python-numpy python-scipy
install: 
  - LANG=C python setup.py develop
script: nosetests -v
