language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install cython python-numpy python-scipy
install: 
  - LANG=C python setup.py develop
script: nosetests -v --logging-level=INFO --logging-clear-handlers --logging-format='%(filename)s:%(lineno)s [%(funcName)s] %(message)s'
